### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [RedBrogdon/voxxedapp#1]
I think we're really missing a serious app example using Bloc. 
Would you PR on awesome flutter for future marks for new comers ?

https://github.com/Solido/awesome-flutter 

Thank you !

**Comment by redbrogdon** [comment]
Absolutely! I'm going to put together a project plan for the next round of features and attempt to transition the app to a community-based project (rather than one for which I am the only coder). Once that's done (hopefully in a week or two), I'll definitely submit it to the list if you're willing to have it on there.

This isn't the latest copy of the code, BTW. That's at:

https://github.com/devoxx/voxxedapp

I need to put a "deprecated" banner on this repo, I think, since it's now being maintained elsewhere.

**Comment by redbrogdon** [comment]
Also, I'm not sure if you've ever noticed, but I put a shout-out for Awesome Flutter in the Flutter team's sample repo a while back:

https://github.com/flutter/samples/blob/master/INDEX.md

It's a really great resource.

**Comment by Solido** [comment]
Hi @RedBrogdon, I just noticed last night !  

During the zoom session, someone posted a link to your Youtube video, this was exactly the kind of material I'm looking for and then in the middle of the show I just 'tilted' on the awesome flutter logo. 
Thanks you very much for the surprise :D 

I started the list as a personal note on the emerging package and best practices and now I'll try to curate it to make it a full developper program. By following it for top to bottom you should be able to grasp the basics, then some results with widgets and lib and finish with understandings of the 3 (20) trees of the framework.

In this aspect you app is good support since you cover Bloc and even the Uber build_ pattern. I'll find some time to enjoy digging into all this. Devoxx should also ring a bell to any serious devs ;)

**Comment by LOG-TAG** [comment]
@RedBrogdon  thanks for the info! any help available solve this error! 
```
[voxxedapp] flutter packages get
Running "flutter packages get" in voxxedapp...                  
Because built_value_generator >=5.5.5 depends on analyzer ^0.32.1 and every version of flutter_test from sdk depends on analyzer 0.33.0, built_value_generator >=5.5.5 is incompatible with flutter_test from sdk.
So, because voxxedapp depends on both flutter_test any from sdk and built_value_generator ^6.1.2, version solving failed.

pub get failed (1)
exit code 1
```

**Comment by redbrogdon** [comment]
Bah, I'm just seeing this now. The issue you mentioned should be corrected now. There was an issue with the most recent version of flutter using one version of the analyzer and built_value requiring another. Had to override the version number, but it's working now.
